Name: Dev Patel 

Course: DS4400 Data Mining and Machine Learning 1

Prof: Silvio Amir

University: Northeastern University 



Problem 4.2: Generate at random 3 matrices of size $3 \times 3$ and fill each entry with a random integer chosen from -10 to 10. Use an existing package to compute the inverse of each matrix if it exists. Include in your report:

    - Each of the 3 matrices
    
    - The inverses computed with the package
    
    - Compute the product of each matrix with its inverse to check that you obtain the identity matrix.

In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(777)

In [3]:
def random_matrix():
    return rng.integers(low=-10, high=11, size=(3, 3))

def show_matrix_blcok(i, A):
    print(f"\n MATRIX {i}")
    print(A)
    
    det = round(np.linalg.det(A))
    print(f"det(A) approx {det}")
    
    A_inv = np.linalg.inv(A)
    print(f"A_inv approx {A_inv}")
    
    prod = A @ A_inv
    print(f"]nA @ A_inv should be identity: {prod}")
    
    print("\nCheck allclose to identity:", np.allclose(prod, np.eye(3)))
        

        

In [4]:
for i in range(1, 4):
    A = random_matrix()
    show_matrix_blcok(i,A)


 MATRIX 1
[[ 9  2 -3]
 [-2 -8  2]
 [-1 10 -4]]
det(A) approx 172
A_inv approx [[ 0.06976744 -0.12790698 -0.11627907]
 [-0.05813953 -0.22674419 -0.06976744]
 [-0.1627907  -0.53488372 -0.39534884]]
]nA @ A_inv should be identity: [[ 1.00000000e+00  0.00000000e+00 -5.55111512e-17]
 [ 1.11022302e-16  1.00000000e+00  2.22044605e-16]
 [-1.11022302e-16  0.00000000e+00  1.00000000e+00]]

Check allclose to identity: True

 MATRIX 2
[[-6 -4 -3]
 [-3  1 -2]
 [ 1  0  5]]
det(A) approx -79
A_inv approx [[-0.06329114 -0.25316456 -0.13924051]
 [-0.16455696  0.34177215  0.03797468]
 [ 0.01265823  0.05063291  0.2278481 ]]
]nA @ A_inv should be identity: [[ 1.00000000e+00 -2.77555756e-16  1.11022302e-16]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [-1.38777878e-17  5.55111512e-17  1.00000000e+00]]

Check allclose to identity: True

 MATRIX 3
[[-9 -1  9]
 [-9  2 -7]
 [ 3  5  0]]
det(A) approx -753
A_inv approx [[-0.04648074 -0.05976096  0.01460823]
 [ 0.02788845  0.03585657  0.19123506]
 [ 0.067